FAB_SIM_IP = altera_mf
PY_TB_VHDL = [ "string_pkg.vhd", "kirsch_synth_pkg.vhd", "kirsch_unsynth_pkg.vhd", "kirsch_tb.vhd" ]
PY_DESIGN_VHDL = [ "mem.vhd", "kirsch_synth_pkg.vhd", "kirsch.vhd", "kirsch_utility_pkg.vhd", "memory.vhd", "flow.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2S15F484C
BOARD = STRATIX
TCL_TB_VHDL = { string_pkg.vhd kirsch_synth_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd }
DESIGN_ENTITY = kirsch
FAMILY_SHORT = StratixII
SH_DESIGN_VHDL = mem.vhd kirsch_synth_pkg.vhd kirsch.vhd kirsch_utility_pkg.vhd memory.vhd flow.vhd
DESIGN_ARCH = main
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
SH_TB_VHDL = string_pkg.vhd kirsch_synth_pkg.vhd kirsch_unsynth_pkg.vhd kirsch_tb.vhd
TB_ENTITY = kirsch_tb
GOAL_FREQ = 500
USE_GUI = False
TB_VHDL = string_pkg.vhd, kirsch_synth_pkg.vhd, kirsch_unsynth_pkg.vhd, kirsch_tb.vhd
SIM_SCRIPT = kirsch_tb.sim
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
RPT_TDIR = RPT
FAMILY_LONG = Stratix II
TCL_DESIGN_VHDL = { mem.vhd kirsch_synth_pkg.vhd kirsch.vhd kirsch_utility_pkg.vhd memory.vhd flow.vhd }
INTERACTIVE_FLAG = False
SPEED = 5
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = kirsch
TB_ARCH = main
LC_FAMILY_SHORT = stratixii
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
DESIGN_VHDL = mem.vhd, kirsch_synth_pkg.vhd, kirsch.vhd, kirsch_utility_pkg.vhd, memory.vhd, flow.vhd
GUI_FLAG = -shell
