FAB_SIM_IP = altera_mf
PY_DESIGN_VHDL = [ "memory.vhd", "mem.vhd", "kirsch_utility_pkg.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2S15F484C
BOARD = STRATIX
DESIGN_ENTITY = memory
FAMILY_SHORT = StratixII
SH_DESIGN_VHDL = memory.vhd mem.vhd kirsch_utility_pkg.vhd
DESIGN_ARCH = main
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
TB_ENTITY = memory_tb
GOAL_FREQ = 500
USE_GUI = False
SIM_SCRIPT = memory_tb.sim
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
RPT_TDIR = RPT
FAMILY_LONG = Stratix II
TCL_DESIGN_VHDL = { memory.vhd mem.vhd kirsch_utility_pkg.vhd }
INTERACTIVE_FLAG = False
DESIGN_VHDL = memory.vhd, mem.vhd, kirsch_utility_pkg.vhd
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = memory
LC_FAMILY_SHORT = stratixii
PHYS_SYNTH_TOOL = QUARTUS
PROG = uw-synth
SPEED = 5
GUI_FLAG = -shell
