FAB_SIM_IP = altera_mf
NUM_TIMING_PATHS = 5
PHYS_SYNTH_EXT = vhd
PIN_FILE = Y:\lib\pins-DE2.tcl
PY_DESIGN_VHDL = [ "mem.vhd", "kirsch_synth_pkg.vhd", "kirsch.vhd", "lib_kirsch.vhd", "top_kirsch.vhd", "kirsch_utility_pkg.vhd", "memory.vhd", "flow.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2C35F672C
BOARD = DE2
DESIGN_ENTITY = top_kirsch
FAMILY_SHORT = CycloneII
SH_DESIGN_VHDL = mem.vhd kirsch_synth_pkg.vhd kirsch.vhd lib_kirsch.vhd top_kirsch.vhd kirsch_utility_pkg.vhd memory.vhd flow.vhd
DESIGN_ARCH = main
FREQ_MIN = 50
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = Y:/
LIB_VHDL = 
SH_LIB_VHDL = 
TB_ENTITY = top_kirsch_tb
GOAL_FREQ = 250
USE_GUI = False
PHYS_SYNTH_TOOL = QUARTUS
RPT_DIR = RPT
FAB_SIM_HOME = Y://altera
LOGIC_SYNTH_EXT = edf
RPT_TDIR = RPT
FAMILY_LONG = Cyclone II
TCL_DESIGN_VHDL = { mem.vhd kirsch_synth_pkg.vhd kirsch.vhd lib_kirsch.vhd top_kirsch.vhd kirsch_utility_pkg.vhd memory.vhd flow.vhd }
INTERACTIVE_FLAG = False
SPEED = 7
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = top_kirsch
LC_FAMILY_SHORT = cycloneii
PROG = uw-synth
TCL_LIB_VHDL = {  }
DESIGN_VHDL = mem.vhd, kirsch_synth_pkg.vhd, kirsch.vhd, lib_kirsch.vhd, top_kirsch.vhd, kirsch_utility_pkg.vhd, memory.vhd, flow.vhd
GUI_FLAG = -shell
PY_LIB_VHDL = []
