FAB_SIM_IP = altera_mf
NUM_TIMING_PATHS = 5
PY_DESIGN_VHDL = [ "max.vhd" ]
PWR_TOOL = QUARTUS
USER_TOOL_FLAGS = 
PART = EP2S15F484C
BOARD = STRATIX
DESIGN_ENTITY = max
FAMILY_SHORT = StratixII
SH_DESIGN_VHDL = max.vhd
DESIGN_ARCH = 
ASIC = False
SIM_TOOL = MODELSIM
GENERICS = {  }
ECE327 = /home/ece327
LIB_VHDL = 
SH_LIB_VHDL = 
GOAL_FREQ = 500
USE_GUI = False
PHYS_SYNTH_TOOL = QUARTUS
RPT_DIR = RPT
FAB_SIM_HOME = /home/ece327/altera
LOGIC_SYNTH_EXT = edf
RPT_TDIR = RPT
FAMILY_LONG = Stratix II
TCL_DESIGN_VHDL = { max.vhd }
INTERACTIVE_FLAG = False
DESIGN_VHDL = max.vhd
LOGIC_SYNTH_TOOL = PRECISION_RTL
UWP = max
LC_FAMILY_SHORT = stratixii
PROG = uw-synth
TCL_LIB_VHDL = {  }
SPEED = 5
GUI_FLAG = -shell
PY_LIB_VHDL = []
